stages:
    - build
    - quality

image: node:latest

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store
    - node_modules/

before_script:
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
    - pnpm config set store-dir .pnpm-store

restore-dependencies:
    stage: build
    script:
        - pnpm install

build-package:
    stage: build
    needs:
        - restore-dependencies
    script:
        - pnpm build
    artifacts:
        paths:
            - dist/

static-typing:
    stage: quality
    script:
        - pnpm type-check

lint:
    stage: quality
    needs:
        - static-typing
    script:
        - pnpm eslint . --ext .vue,.js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts --fix --ignore-path .gitignore

test:
    stage: quality
    script:
        - pnpm vitest